#!/bin/bash
echo "🚀 Запуск Trench..."
echo ""
echo "Доступные команды:"
echo "  trench search <query>           - Поиск в интернете"
echo "  trench code <query>             - Поиск кода на GitHub"
echo "  trench papers <query>           - Поиск научных статей"
echo "  trench community <query>        - Поиск в HN/Reddit"
echo "  trench research <query>         - Глубокое исследование"
echo ""
echo "Пример использования:"
echo "  trench research \"React Server Components\""
echo ""
trench research "How to build AI agents"
