/**
 * Constants for Java Language Support
 */

// Maven lifecycle phases
export const MAVEN_LIFECYCLE_PHASES = {
  CLEAN: ['pre-clean', 'clean', 'post-clean'],
  DEFAULT: [
    'validate',
    'initialize',
    'generate-sources',
    'process-sources',
    'generate-resources',
    'process-resources',
    'compile',
    'process-classes',
    'generate-test-sources',
    'process-test-sources',
    'generate-test-resources',
    'process-test-resources',
    'test-compile',
    'process-test-classes',
    'test',
    'prepare-package',
    'package',
    'pre-integration-test',
    'integration-test',
    'post-integration-test',
    'verify',
    'install',
    'deploy'
  ],
  SITE: ['pre-site', 'site', 'post-site', 'site-deploy']
} as const;

// Common Maven goals with descriptions
export const MAVEN_GOALS: Record<string, { description: string; common: boolean }> = {
  'clean': { description: 'Remove all files generated by the previous build', common: true },
  'validate': { description: 'Validate the project is correct', common: false },
  'compile': { description: 'Compile the source code of the project', common: true },
  'test': { description: 'Run tests using a suitable unit testing framework', common: true },
  'package': { description: 'Package compiled code into distributable format', common: true },
  'verify': { description: 'Run any checks to verify the package is valid', common: false },
  'install': { description: 'Install the package into the local repository', common: true },
  'deploy': { description: 'Copy the final package to the remote repository', common: false },
  'site': { description: 'Generate project documentation', common: false },
  
  // Plugin goals
  'dependency:tree': { description: 'Display the dependency tree', common: true },
  'dependency:analyze': { description: 'Analyze the project dependencies', common: false },
  'dependency:sources': { description: 'Resolve and download sources', common: true },
  'help:effective-pom': { description: 'Display the effective POM', common: false },
  'help:active-profiles': { description: 'List active profiles', common: false },
  'javadoc:javadoc': { description: 'Generate Javadoc', common: false },
  'checkstyle:check': { description: 'Run Checkstyle analysis', common: false },
  'spotbugs:spotbugs': { description: 'Run SpotBugs analysis', common: false }
};

// Common Gradle tasks with descriptions
export const GRADLE_TASKS: Record<string, { description: string; group: string; common: boolean }> = {
  'build': { description: 'Assembles and tests this project', group: 'Build', common: true },
  'clean': { description: 'Deletes the build directory', group: 'Build', common: true },
  'assemble': { description: 'Assembles the outputs of this project', group: 'Build', common: true },
  'check': { description: 'Runs all checks', group: 'Verification', common: true },
  'test': { description: 'Runs the unit tests', group: 'Verification', common: true },
  'classes': { description: 'Assembles main classes', group: 'Build', common: true },
  'testClasses': { description: 'Assembles test classes', group: 'Build', common: false },
  'jar': { description: 'Assembles a jar archive', group: 'Build', common: true },
  'war': { description: 'Assembles a war archive', group: 'Build', common: false },
  'javadoc': { description: 'Generates Javadoc API documentation', group: 'Documentation', common: true },
  'publish': { description: 'Publishes artifacts to repositories', group: 'Publishing', common: false },
  'publishToMavenLocal': { description: 'Publishes to local Maven repository', group: 'Publishing', common: false },
  'dependencies': { description: 'Displays all dependencies', group: 'Help', common: true },
  'dependencyInsight': { description: 'Displays insight into a specific dependency', group: 'Help', common: false },
  'projects': { description: 'Displays sub-projects', group: 'Help', common: false },
  'tasks': { description: 'Displays available tasks', group: 'Help', common: true },
  'wrapper': { description: 'Generates Gradle wrapper files', group: 'Build Setup', common: false },
  'init': { description: 'Initializes a new Gradle build', group: 'Build Setup', common: false },
  'buildEnvironment': { description: 'Displays buildscript dependencies', group: 'Help', common: false },
  'components': { description: 'Displays components produced by root project', group: 'Help', common: false },
  'model': { description: 'Displays configuration model', group: 'Help', common: false },
  'properties': { description: 'Displays project properties', group: 'Help', common: false }
};

// Gradle task groups for organization
export const GRADLE_TASK_GROUPS = [
  'Build',
  'Build Setup',
  'Documentation',
  'Help',
  'Publishing',
  'Verification',
  'Other'
] as const;

// Java keywords for syntax highlighting and completions
export const JAVA_KEYWORDS = [
  'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char',
  'class', 'const', 'continue', 'default', 'do', 'double', 'else', 'enum',
  'extends', 'final', 'finally', 'float', 'for', 'goto', 'if', 'implements',
  'import', 'instanceof', 'int', 'interface', 'long', 'native', 'new',
  'package', 'private', 'protected', 'public', 'return', 'short', 'static',
  'strictfp', 'super', 'switch', 'synchronized', 'this', 'throw', 'throws',
  'transient', 'try', 'void', 'volatile', 'while',
  // Literals
  'true', 'false', 'null',
  // Java 9+
  'module', 'requires', 'exports', 'opens', 'uses', 'provides', 'with', 'to', 'transitive',
  // Java 10+
  'var',
  // Java 13+
  'yield',
  // Java 14+
  'record',
  // Java 16+
  'sealed', 'permits', 'non-sealed'
] as const;

// Common Java types for completions
export const JAVA_COMMON_TYPES = {
  // Primitive wrappers
  primitives: ['Object', 'String', 'Integer', 'Long', 'Double', 'Float', 'Boolean', 'Byte', 'Short', 'Character'],
  
  // Collections
  collections: [
    'List', 'ArrayList', 'LinkedList',
    'Set', 'HashSet', 'LinkedHashSet', 'TreeSet',
    'Map', 'HashMap', 'LinkedHashMap', 'TreeMap', 'ConcurrentHashMap',
    'Queue', 'Deque', 'PriorityQueue', 'ArrayDeque',
    'Collection', 'Collections', 'Arrays'
  ],
  
  // I/O
  io: [
    'File', 'Path', 'Paths', 'Files',
    'InputStream', 'OutputStream', 'Reader', 'Writer',
    'BufferedReader', 'BufferedWriter', 'PrintStream',
    'FileInputStream', 'FileOutputStream',
    'IOException'
  ],
  
  // Concurrency
  concurrency: [
    'Thread', 'Runnable', 'Callable', 'Future', 'CompletableFuture',
    'Executor', 'ExecutorService', 'Executors',
    'Lock', 'ReentrantLock', 'Semaphore', 'CountDownLatch',
    'AtomicInteger', 'AtomicLong', 'AtomicReference'
  ],
  
  // Stream API
  streams: [
    'Stream', 'IntStream', 'LongStream', 'DoubleStream',
    'Collectors', 'Optional', 'OptionalInt', 'OptionalLong', 'OptionalDouble'
  ],
  
  // Utilities
  util: [
    'Objects', 'StringBuilder', 'StringBuffer',
    'Date', 'Calendar', 'LocalDate', 'LocalTime', 'LocalDateTime', 'Instant',
    'UUID', 'Random', 'Scanner', 'Formatter'
  ],
  
  // Annotations
  annotations: [
    'Override', 'Deprecated', 'SuppressWarnings',
    'FunctionalInterface', 'SafeVarargs'
  ],
  
  // Test (JUnit)
  test: [
    'Test', 'Before', 'After', 'BeforeClass', 'AfterClass',
    'BeforeEach', 'AfterEach', 'BeforeAll', 'AfterAll',
    'Assert', 'Assertions', 'Assume', 'Assumptions'
  ]
};

// Java modifiers
export const JAVA_MODIFIERS = {
  access: ['public', 'private', 'protected'],
  nonAccess: [
    'static', 'final', 'abstract', 'synchronized', 'native',
    'strictfp', 'transient', 'volatile'
  ]
} as const;

// File patterns
export const JAVA_FILE_PATTERNS = {
  source: ['**/*.java'],
  test: ['**/test/**/*.java', '**/src/test/**/*.java'],
  resources: ['**/src/main/resources/**/*', '**/src/test/resources/**/*'],
  build: {
    maven: ['pom.xml', '**/pom.xml'],
    gradle: ['build.gradle', 'build.gradle.kts', 'settings.gradle', 'settings.gradle.kts']
  }
} as const;

// JDK detection paths by platform
export const JDK_DETECTION_PATHS = {
  darwin: [
    '/Library/Java/JavaVirtualMachines',
    '/System/Library/Java/JavaVirtualMachines'
  ],
  win32: [
    'C:\\Program Files\\Java',
    'C:\\Program Files\\Eclipse Adoptium',
    'C:\\Program Files\\Amazon Corretto',
    'C:\\Program Files\\Microsoft'
  ],
  linux: [
    '/usr/lib/jvm',
    '/usr/java'
  ]
} as const;

// Error messages
export const ERROR_MESSAGES = {
  JDK_NOT_FOUND: 'No JDK found. Please set JAVA_HOME or configure java.home',
  MAVEN_NOT_FOUND: 'Maven project detected but mvn command not found',
  GRADLE_NOT_FOUND: 'Gradle project detected but gradle command not found',
  BUILD_FAILED: 'Build failed',
  FORMATTER_NOT_FOUND: 'Formatter not found',
  JDTLS_NOT_FOUND: 'JDT Language Server not found',
  INVALID_JDK_PATH: 'Invalid JDK path'
} as const;
