/**
 * Kimi IDE Extension - Utils Module
 * Central export point for all utility functions
 */

// Logger
export {
    logger,
    Logger,
    LogLevel,
    logError,
    logDuration,
    logDurationAsync,
} from './logger';

// File Utils
export {
    FileEncoding,
    readFile,
    readFileFromUri,
    isBinaryFile,
    isTextFile,
    isGitIgnored,
    findFiles,
    getFileInfo,
    getAllFiles,
    getFileExtension,
    getLanguageId,
    formatFileSize,
    detectEncoding,
    type ReadFileOptions,
    type FileInfo,
} from './fileUtils';

// Editor Utils
export {
    getActiveEditor,
    hasActiveEditor,
    getSelection,
    getAllSelections,
    getSelectedTextOrLine,
    getCursorContext,
    insertText,
    replaceSelection,
    replaceDocumentContent,
    openFile,
    createNewFile,
    goToLine,
    getWordAtPosition,
    getDocumentLanguage,
    getDocumentText,
    getVisibleRanges,
    isDirty,
    formatDocument,
    getIndentationSettings,
    createIndentation,
    type CursorContext,
    type SelectionInfo,
    type InsertOptions,
} from './editorUtils';

// Markdown Utils
export {
    extractCodeBlocks,
    extractCodeBlockOfLanguage,
    normalizeLanguage,
    hasIncompleteCodeBlocks,
    countOpenCodeBlocks,
    completeCodeBlocks,
    escapeHtml,
    unescapeHtml,
    renderMarkdownToHtml,
    simpleMarkdownToHtml,
    createMarkdownString,
    stripMarkdown,
    truncateMarkdown,
    formatCodeBlock,
    detectLanguage,
    cleanMarkdownResponse,
    splitByHeaders,
    type CodeBlock,
    type MarkdownOptions,
} from './markdownUtils';

// Async Utils
export {
    createCancelToken,
    makeCancelable,
    debounce,
    throttle,
    throttleWithTrailing,
    retry,
    withTimeout,
    sleep,
    runSequentially,
    runWithConcurrency,
    nextAnimationFrame,
    createDeferred,
    RateLimiter,
    AsyncMutex,
    yieldControl,
    isCancellationError,
    safeAsync,
    type CancelToken,
    type CancelablePromise,
    type DebouncedFunction,
    type ThrottledFunction,
    type RetryOptions,
    type TimeoutOptions,
} from './asyncUtils';

// Types
export {
    type MessageRole,
    type Message,
    type ToolCall,
    type ToolResult,
    type ModelConfig,
    type CompletionOptions,
    type CompletionResponse,
    type StreamingChunk,
    type FileContext,
    type WorkspaceContext,
    type ContextProvider,
    type ChatSession,
    type ChatSettings,
    type CommandDefinition,
    type QuickAction,
    type PanelType,
    type PanelState,
    type WebviewMessage,
    type ExtensionSettings,
    type SettingsSection,
    type TerminalCommand,
    type TerminalResult,
    type TerminalSession,
    type EventHandlers,
    type Nullable,
    type Optional,
    type DeepPartial,
    type AsyncReturnType,
    type Disposable,
    type Cancellable,
    type LoadingState,
    type StatusInfo,
    type DiffBlock,
    type FileDiff,
    type SearchResult,
    type SearchOptions,
    type ProviderCapabilities,
    type ProviderConfig,
    KimiError,
    ErrorCode,
} from './types';

// Constants
export {
    EXTENSION_ID,
    EXTENSION_NAME,
    EXTENSION_DISPLAY_NAME,
    Commands,
    ConfigKeys,
    Defaults,
    ViewIds,
    TreeViewIds,
    WebviewIds,
    ContextKeys,
    StorageKeys,
    Models,
    Providers,
    ProviderUrls,
    UI,
    SystemPrompts,
    QuickActions,
    ErrorMessages,
    Events,
    FilePatterns,
    Regex,
    API,
} from './constants';
